-- MENSAJERIA MX - SQL COMPLETO
-- Ejecuta TODO este archivo en Supabase SQL Editor.
-- Antes activa Authentication -> Sign In / Providers ->
-- Allow anonymous sign-ins.

create table if not exists public.chat_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists chat_profiles_username_unique
on public.chat_profiles (lower(username));

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_created_at_idx
on public.chat_messages(created_at);

alter table public.chat_profiles enable row level security;
alter table public.chat_messages enable row level security;

-- PERFILES
drop policy if exists "chat_profiles_select" on public.chat_profiles;
drop policy if exists "chat_profiles_insert" on public.chat_profiles;
drop policy if exists "chat_profiles_update" on public.chat_profiles;

create policy "chat_profiles_select"
on public.chat_profiles for select
to authenticated
using (true);

create policy "chat_profiles_insert"
on public.chat_profiles for insert
to authenticated
with check (auth.uid() = user_id);

create policy "chat_profiles_update"
on public.chat_profiles for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- MENSAJES
drop policy if exists "chat_messages_select" on public.chat_messages;
drop policy if exists "chat_messages_insert" on public.chat_messages;

create policy "chat_messages_select"
on public.chat_messages for select
to authenticated
using (true);

create policy "chat_messages_insert"
on public.chat_messages for insert
to authenticated
with check (auth.uid() = user_id);

grant select, insert, update on public.chat_profiles to authenticated;
grant select, insert on public.chat_messages to authenticated;

-- REALTIME
do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception
  when duplicate_object then null;
end $$;

alter table public.chat_messages replica identity full;

-- COMPROBACIÓN
select * from public.chat_profiles order by created_at desc;
select * from public.chat_messages order by created_at desc limit 20;
